# Generated by Django 5.0.3 on 2024-03-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_channels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servers',
            old_name='memebers',
            new_name='members',
        ),
    ]
